{% set name = "mkdocs-click" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs_click-{{ version }}.tar.gz
  sha256: b34be84cde57850733fb1b32db37b472620ac2c3e97db4abbe11dbd6b98124f2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click >=7, <8
    - markdown >=3, <4

test:
  imports:
    - mkdocs_click

about:
  home: https://github.com/DataDog/mkdocs-click
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: MkDocs extension for Click
  description: An MkDocs extension to generate documentation for Click command line applications.
  doc_url: https://github.com/DataDog/mkdocs-click
  dev_url: https://github.com/DataDog/mkdocs-click

extra:
  recipe-maintainers:
    - JorgeGarciaIrazabal
